### ISSUE TITLE
Overflow errors when resizing the board

### ISSUE THREAD

**Issue by deathcoder** [alexobviously/squares#14]
This isn't a major problem, but is one that's been bugging me for some time while developing, 
in my project i wrap the `Board` widget in a `Flexible` widget to make it's size responsive and adapt to the available space on the screen, but in debug mode when i resize the screen there will be a split second in which the board overflows and overflow errors are logged into the console... i have looked a bit into it and at first i thought i was doing something wrong, or that this was related by the interaction between `Flexible` and `AspectRatio` which is the first layer of `Board`... but then i tested it with simple containers and they don't overflow when they are inserted into `Flexible` and `AspectRatio`... looking this up online i found resources suggesting to use `OverflowBox` or even combine it with `IntrinsicWidth` and `IntrinsicHeight` but i couldn't make this work without losing some of the `Flexible` features... so now i'm thinking that the problem should be further down the tree maybe `LayoutBuilder` or `Stack` are failing to update properly... anyway if you have any solution to this please let me know

Here is a flutter issue describing a similar problem: https://github.com/flutter/flutter/issues/100789

I will keep updating with what i find:
Update 1: i have isolated the problem to be within `BoardBackground`, if i replace it with a `Container` i don't see overflow errors anymore and everything else works fine

Update 2: i fixed the problem by changing the `AnimatedContainer` to a simple `Container` in `board_background.dart` i'm opening a PR for this, everything seems to work fine for my use case but i'm not sure if this breaks some other requirement

**Comment by alexobviously** [comment]
Yeah I've also been annoyed by this when working with Squares on web, and I'm currently building a webapp with it so thanks for figuring out what's going on.

**Comment by alexobviously** [comment]
Hey, I found a way to do this without removing the animation, see this commit: https://github.com/alexobviously/squares/commit/a78ef71a6cb9cab75e1eda068f69078c38e95614

So can you try that out and see if it works for you (use dev branch, not on main yet), and if so then we can close your issue and PR and I'll release

**Comment by deathcoder** [comment]
can confirm `dev` branch works without overflow errors 🙌

**Comment by alexobviously** [comment]
Excellent, I'll close this and your PR then and release `1.1.4`
