### ISSUE TITLE
Allow pre-moves with drag gesture and not only tap gesture.

### ISSUE THREAD

**Issue by Bolling88** [alexobviously/squares#16]
As the title states, it would be nice if we could add pre-moves with drag gestures and not only tap gestures.

**Comment by alexobviously** [comment]
Sure, that's a good idea. I'll take a look tomorrow and see what this would involve.

**Comment by alexobviously** [comment]
Hey @Bolling88, actually premoves with dragging already works lol. I don't know why I thought that wasn't the case but yeah premoves from dragging using `BoardController` has been in since at least `1.0.0`.
If you can't make premoves with dragging then it's definitely a bug, can you check again?

**Comment by alexobviously** [comment]
@Bolling88 I'm going to close this, let me know if you have any problems after updating
