### ISSUE TITLE
Prediction move issue

### ISSUE THREAD

**Issue by RawadZogheib** [alexobviously/squares#19]
When it's not my turn and I click on any piece. it show me the move of this piece like there is no other piece on the table (when it's. not my turn) but if do. this and my turn comes, it keep showing that.
like shower in. the video

https://user-images.githubusercontent.com/89975932/229270379-14cc62a9-ab98-4968-9e67-172cbd332c8e.mov

**Comment by alexobviously** [comment]
Thanks for the report!
I've just fixed this - update to `1.1.5` and you shouldn't see this bug any more.

Fixed in https://github.com/alexobviously/squares/commit/407df468f2a7d9ca637fac686d547718bd5ebc54#diff-3d5401ee74d889b7d57bb8c3bb981ea25f7d6d30477e716f4760762dbda2b8aeR228

**Comment by alexobviously** [comment]
@RawadZogheib I'm going to close this because, as far as I can see, it's fixed. If you have any further problems feel free to comment and I'll reopen this ticket.
