### ISSUE TITLE
Rank and file numbers on board

### ISSUE THREAD

**Issue by alexobviously** [alexobviously/squares#5]
Can be included in `BoardBackground` I think, no need for another layer.

**Comment by ThomasKaputa** [comment]
Hi @alexobviously 
Do you want any help on this? Working on something like this
![image](https://user-images.githubusercontent.com/54510958/192856324-9ccb8874-9575-463d-bfe7-79521d3a17ce.png)

PR's should be made on dev right?

**Comment by alexobviously** [comment]
@ThomasKaputa Hey, thanks for the contribution! However, I actually have already built this feature, just hadn't committed it: https://github.com/alexobviously/squares/commit/6b5a88d45b2cc59a72ecca9e36c63d45e1c78a08
I'm currently trying to find a way to improve the alignment of the labels, especially on the bottom with characters that don't have descenders, so if you have an idea about that it would be appreciated.

In general though yes I would happily accept contributions on this project, and you can make PRs to `main` - `dev` is just my personal working branch.

**Comment by ThomasKaputa** [comment]
@alexobviously 
Okay, thanks for your reply.

I don't have a special Idea at the moment but the alignment looks fine to me, on the default 8x8 board on chrome at least.

I will keep my eyes open and try to contribute something 👍

**Comment by alexobviously** [comment]
This is done now and live in 1.0.4!
