### ISSUE TITLE
Allow for unplayable space on the board, e.g. the river in Xiangqi

### ISSUE THREAD

**Issue by alexobviously** [alexobviously/squares#9]

**Comment by malaschitz** [comment]
River in XiangQi is not "unplayable". In fact, it is just an altered graphic - no lines are drawn between the points to highlight the rules of the game (pawn, elephant). But the pieces normally pass through this territory. In XiangQi, there are several similar problems:
- diagonals are drawn in the "castle"
- very often the points where the pawns and cannons are at the beginning of the game are graphically highlighted. 

For the flutter implementation, there are no standard squares for the pieces in the dot squares. Respectively, these fields are invisible.

**Comment by alexobviously** [comment]
Ah you are right, in my head I imagined the river as twice the height it actually is. Okay so that simplifies things a lot. I'm closing this because it's not needed (at least until someone finds a variant that does need it)
